### PR TITLE
New styling

### PR DESCRIPTION
**Pull request by davidyuk**

### CODE REVIEW

**Comment by ducdev** [comment]
image
Text is a bit on top, please adjust padding ?

**Comment by ducdev** [comment]
Apart from that, styling changes are beautiful indeed. You can go merging it. @davidyuk

**Comment by ducdev** [comment]
image
But wait, when I click on disagree, the agree button is not losing active state ?

**Comment by davidyuk** [comment]
> Text is a bit on top, please adjust padding?

These paddings are from the style guide. As I understand the height of comments box is a hint to the ability of multi-line comments.

> But wait, when I click on disagree, the agree button is not losing active state?

This should appear when you agreed with the statement and then clicked at disagree button. Both of buttons are `active`, the first one is because you have agreed before and the second since you are going to disagree with this statement. It is lack of the style guide.

**Comment by ducdev** [comment]
Ya, then that's fine, please go ahead. @davidyuk

**Pull request merged**
